const gamesData = [
  {title: "Jeux de rôles et semi-GN",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, turpis sed ultrices congue, nibh libero iaculis dolor, vel posuere ipsum lacus eu sapien. Aliquam ac nibh eget quam pellentesque lacinia ac non lorem. Cras non quam purus. Fusce non dolor urna. Vivamus sollicitudin feugiat condimentum. Aenean sodales lorem diam, lacinia fermentum lectus semper eu. Nam elementum tellus ac elit imperdiet efficitur. Phasellus ut dui a lectus blandit malesuada. Nam iaculis enim quis pellentesque tempor. Nunc semper odio vitae leo malesuada, id porta elit elementum. Vivamus id eleifend ligula, a molestie dui. "},
  {title: "Jeux traditionnels",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, turpis sed ultrices congue, nibh libero iaculis dolor, vel posuere ipsum lacus eu sapien. Aliquam ac nibh eget quam pellentesque lacinia ac non lorem. Cras non quam purus. Fusce non dolor urna. Vivamus sollicitudin feugiat condimentum. Aenean sodales lorem diam, lacinia fermentum lectus semper eu. Nam elementum tellus ac elit imperdiet efficitur. Phasellus ut dui a lectus blandit malesuada. Nam iaculis enim quis pellentesque tempor. Nunc semper odio vitae leo malesuada, id porta elit elementum. Vivamus id eleifend ligula, a molestie dui. "},
  {title: "Jeux de stratégie",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, turpis sed ultrices congue, nibh libero iaculis dolor, vel posuere ipsum lacus eu sapien. Aliquam ac nibh eget quam pellentesque lacinia ac non lorem. Cras non quam purus. Fusce non dolor urna. Vivamus sollicitudin feugiat condimentum. Aenean sodales lorem diam, lacinia fermentum lectus semper eu. Nam elementum tellus ac elit imperdiet efficitur. Phasellus ut dui a lectus blandit malesuada. Nam iaculis enim quis pellentesque tempor. Nunc semper odio vitae leo malesuada, id porta elit elementum. Vivamus id eleifend ligula, a molestie dui. "},
  {title: "Jeux de figurines",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, turpis sed ultrices congue, nibh libero iaculis dolor, vel posuere ipsum lacus eu sapien. Aliquam ac nibh eget quam pellentesque lacinia ac non lorem. Cras non quam purus. Fusce non dolor urna. Vivamus sollicitudin feugiat condimentum. Aenean sodales lorem diam, lacinia fermentum lectus semper eu. Nam elementum tellus ac elit imperdiet efficitur. Phasellus ut dui a lectus blandit malesuada. Nam iaculis enim quis pellentesque tempor. Nunc semper odio vitae leo malesuada, id porta elit elementum. Vivamus id eleifend ligula, a molestie dui. "},
  {title: "Animations",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, turpis sed ultrices congue, nibh libero iaculis dolor, vel posuere ipsum lacus eu sapien. Aliquam ac nibh eget quam pellentesque lacinia ac non lorem. Cras non quam purus. Fusce non dolor urna. Vivamus sollicitudin feugiat condimentum. Aenean sodales lorem diam, lacinia fermentum lectus semper eu. Nam elementum tellus ac elit imperdiet efficitur. Phasellus ut dui a lectus blandit malesuada. Nam iaculis enim quis pellentesque tempor. Nunc semper odio vitae leo malesuada, id porta elit elementum. Vivamus id eleifend ligula, a molestie dui. "}
]

export default gamesData