const partnersData = [
  {
    name: "Mairie de Perpignan",
    description: "Mairie de Perpignan - Hôtel de Ville",
    list: [],
    other: "",
    contact: {
      admin: "",
      location: "Place de la loge",
      city: "66000 Perpignan Cedex",
      map: "https://goo.gl/maps/1Y98C1h6hDa3wMMY8",
      phone: "",
      email: "",
      webpage: "https://www.mairie-perpignan.fr/",
    },
    picture: "pictures/partners/LOGO-Mairie-de-Perpignan-1.png",
    alt: "logo de la mairie de Perpignan",
    width: 210,
    height: 260,
    style: { name: { textAlign: "center" } },
  },
  {
    name: "Aviva Assurances",
    description: "Aviva Assurances",
    list: [],
    other: "Morad Oubaya - Agent Général",
    contact: {
      admin: "Morad Oubaya",
      location: "9 Rue du docteur Pous",
      city: "66000 Perpignan",
      map: "https://goo.gl/maps/TpsrkJNA5hSKjH2L7",
      phone: "04-68-51-25-25",
      email: "perpignanroussillon@aviva-assurances.com",
      webpage: "https://agences.aviva.fr/perpignan-roussillon/",
    },
    picture: "/pictures/partners/aviva.png",
    alt: "logo des assurances Aviva",
    width: 260,
    height: 260,
    style: { name: { textAlign: "center" }, other: { textAlign: "center" } },
  },
  {
    name: "L'As du Roi",
    description:
      "L'As du Roi est une boutique spécialisée dans laquelle vous pourrez trouver :",
    list: [
      "des jeux de société (de plateau)",
      "des jeux de cartes",
      "des puzzles",
      "des jeux en bois",
      "des jeux d'échec",
      "des maquettes en bois/métal/carton",
      "des jeux inédits créés sur place",
    ],
    other: "N'hésitez pas à venir nous rendre visite ! A bientôt !",
    contact: {
      admin: "Jérôme Galindo",
      location: "49 Rue Maréchal Foch",
      city: "66000 Perpignan",
      map: "https://goo.gl/maps/9eYg2HDGVprbw36JA",
      phone: "06-02-32-48-19",
      email: "",
      webpage: "http://www.asduroi.fr",
    },
    picture: "/pictures/partners/asduroi.jpg",
    alt: "logo du magasin l'As du roi",
    width: 260,
    height: 260,
    style: {},
  },
  {
    name: "2AM System",
    description:
      "Vente, installation et dépannage de systèmes et logiciels de caisse, TPV et tiroirs sécurisés dans les Pyrénées-Orientales",
    list: [],
    other:
      "Experts en systèmes de caisse, TPV, TPE… Au service des professionnels. Vous apporter les meilleurs conseils est notre priorité. Nous mettons tout en œuvre afin de vous équiper au mieux en fonction de vos besoins.",
    contact: {
      admin: "Marc Jalmain",
      location: "5 Place Louis Torcatis",
      city: "66240 Saint-Estève",
      map: "https://g.page/2AMSYSTEM?share",
      phone: "09-73-10-33-24",
      email: "",
      webpage: "https://www.2amsystem66.fr",
    },
    picture: "/pictures/partners/2amsystem.png",
    alt: "logo de la société 2AM System",
    width: 260,
    height: 260,
    style: { other: { marginTop: "1rem" } },
  },
  {
    name: "REC BAND Production",
    description: "",
    list: [
      "YouTubeur",
      "Cadreur",
      "Photographe",
      "Motion designer",
      "Animateur",
      "Étalonneur",
      "Chorégraphe de combat",
      "Créateur d'univers de jeu",
      "Réalisateur",
      "Metteur en scène",
    ],
    other: "",
    contact: {
      admin: "Josselyn Baudiquey",
      location: "",
      city: "",
      map: "",
      phone: "",
      email: "rec.band.prod@gmail.com",
      webpage: "https://www.facebook.com/RECBANDPRODUCTION/",
    },
    picture: "/pictures/partners/recband.png",
    alt: "logo de rec banc production",
    width: 260,
    height: 260,
    stlyle: {},
  },
  {
    name: "Sortilèges Gourmands",
    description: "Sortilèges Gourmands",
    list: [],
    other: "Christophe Pimont - Pâtissier Chocolatier",
    contact: {
      admin: "Christophe Pimont",
      location: "83 Bld Aristide Briand",
      city: "66000 Perpignan",
      map: "https://g.page/sortileges-gourmands?share",
      phone: "",
      email: "",
      webpage: "https://www.sortilegesgourmands.fr/",
    },
    picture: "/pictures/partners/sortileges-gourmands.jpg",
    alt: "logo de l'entreprise Sortilèges Gourmands",
    width: 260,
    height: 260,
    style: { name: { textAlign: "center" }, other: { textAlign: "center" } },
  },
  {
    name: "Ludiconcept",
    description:
      "Fondé par Mathieu Baiget, édition et création de jeux développés dans les Pyrénées-Orientales. Ce qui rend nos jeux uniques :",
    list: [
      "Des jeux d'auteurs français, 100% originaux",
      "Des thématiques fortes et immersives",
      "Des jeux modulaires qui s'adaptent à vos envies",
    ],
    other:
      "Ludiconcept propose une gamme grand public et des créations sur mesure pour les professionnels.",
    contact: {
      admin: "Mathieu Baiget",
      location: "6 place de la République",
      city: "66270 Le Soler",
      map: "https://g.page/ludiconcept?share",
      phone: "",
      email: "",
      webpage: "https://www.ludiconcept.fr/",
    },
    picture: "/pictures/partners/logo-ludi-concept.png",
    alt: "logo de l'entreprise Ludiconcept",
    width: 260,
    height: 260,
    style: {},
  },
  {
    name: "Chez Fati",
    description: "Traiteur - Chez Fati",
    list: [],
    other: "",
    contact: {
      admin: "",
      location: "45 rue du Maréchal Foch",
      city: "66000 Perpignan",
      map: "https://goo.gl/maps/PLcfxeTfbYS2t7Fp6",
      phone: "",
      email: "",
      webpage: "",
    },
    picture: "/pictures/partners/logo-fati.png",
    alt: "logo du traiteur Chez Fati",
    width: 260,
    height: 260,
    style: { name: { textAlign: "center" } },
  },
  /* 
  {
    name: "",
    description: "",
    list: [],
    other: "",
    contact: {
      admin: "",
      location: "",
      map: "",
      phone: "",
      email: "",
      webpage: ""
    },
    picture: "/pictures/partners/XXXXX",
    alt: "",
    width: 260,
    height: 260,
    style: {}
  } */
];

export default partnersData;
